### ISSUE TITLE
Typo in wiki

### ISSUE THREAD

**Issue by tyluRp** [eblondel/geosapi#28]
I think there is a minor typo in the [**wiki**](https://github.com/eblondel/geosapi/wiki#GSFeatureType).

```
md1 <- GSMetadataLink$new(type = "text/xml", metadataType = "ISO19115:2003", content = "http://somelink.org/xml")
featureType$addMetadataLink(md)
```

Where `featureType$addMetadataLink(md)` should be `featureType$addMetadataLink(md1)`

**Comment by eblondel** [comment]
Thanks, i've fixed it.
