### ISSUE TITLE
unpublishLayer doc

### ISSUE THREAD

**Issue by fxi** [eblondel/geosapi#34]
Hi,

There is a typo in doc version `0.3-0` . For `unpublishLayer`, it gives us 4 parameters, but the function takes only 3.

code:
```R
 gsman$unpublishLayer
function (ws, ds, lyr)
{
    self$INFO(sprintf("Unpublishing layer '%s'", lyr))
    unpublished <- FALSE
    (...)
    return(unpublished)
}
```
doc:

> ‘unpublishLayer(ws, ds, featureType, layer)’ Unpublish a web-layer (including the featureType and 'layer' resources), given a workspace, a datastore, and a layer name

As I am here, is there a way to enable services by workspace ? Example, WMS but not WCS or only WMS ? The API seems to give us something [like that](https://docs.geoserver.org/stable/en/user/rest/api/workspaces.html) with `/workspaces/<ws>/settings`, but what would be the strategy from `geosapi` ?

Thanks !

**Comment by eblondel** [comment]
Thanks @fxi i've fixed the Rdoc.

For what concerns your request, Settings management seems indeed supported by the API, but this feature is not (yet) part of geosapi.

**Comment by fxi** [comment]
That was quick :)
I will speak with my team to see what we can do to contribute bounty-wise or code-wise.
Thanks !
