### ISSUE TITLE
Republish an unpublished layer. Geoserver or geosapi issue ?

### ISSUE THREAD

**Issue by fxi** [eblondel/geosapi#43]
Hi, again.

Using the functions `gsman$publishLayer and gsman$unpublishLayer` there is a small issue, maybe related to geoserver cache or something.

If I publish a layer, then unpublish it, the re-publish it with the same name, I've got an error : 

```java
2018-12-20 14:27:25,190 ERROR [geoserver.rest] - Resource named '<name>' already exists in store: '<my_pg_store>'
````
No layer names are returned.
```r
> gsman$getLayerNames()
list()
```
But if I remove the geoserver from my docker stack, the re-add it, I'm able to republish my layer.

Is that a glitch in `unpublishLayer` or is it a bug in GeoServer ? Or am I missing something ?

Thanks,

F

**Comment by eblondel** [comment]
when unpublishing the layer, did you get TRUE as output, and the following info messages:

```R
[geosapi][INFO] Successfuly deleted layer!
[geosapi][INFO] Successfuly deleted feature type!
[geosapi][INFO] Successfully unpublished layer!
```
The term ``layer`` in Geoserver is ambiguous as it both refers to one particular geoserver web resource ``layer`` associated to the ``feature type`` (connection to the datastore); and the association of layer/feature. ``unpublishLayer``, if successful, should then delete 2 resources the ``layer`` resource, and the ``feature type``.

It could be that one of the ``layer`` or ``feature type`` has not been deleted correctly. In that case you can invoke separately ``$deleteLayer`` or ``$deleteFeatureType`` method.

Finally, if it's a cache issue, you could try to invoke ``$reload()`` that will make Geoserver reload the catalog.

**Comment by eblondel** [comment]
Similar as you did check, you can invoke ``getFeatureTypeNames`` to see if the feature type is still there. It's possibly one reason you didn't succeed to republish the couple layer/feature type. You might need to check further why the feature type has not been deleted.

**Comment by fxi** [comment]
Ok.

I did not get the verbose mode enabled. Is that something like `gMan$verbose.info <- TRUE`  or there is an option somewhere else ?

Then, strangely enough : 

- `$reload()` Worked each time. A lot of unfriendly messages in geoserver, but at least, I was able to republish unpublished layer.
- `$deleteLayer` followed by `$deleteFeatureType` achieved the same result, without unfriendly message.

On my side, I've made a wrapper like bellow and I will retry `unpublishLayer` later.

```R
   (...)
    # 
    # Unpublish layer without unpublishLayer
    #
    layerNames <- gsman$getLayerNames()
    featureTypeNames <- gsman$getFeatureTypeNames( idWorkspace, idDataSource )
    layerName <- idWorkspace + ":" + idLayer
    rmLayer <- layerName %in% layerNames
    rmFeatureType <- idLayer %in% featureTypeNames
   
    if( rmLayer ){
      layerRemoved <- gsman$deleteLayer( layerName )
    }
  
    if( rmFeatureType ){
      featureTypeRemoved <- gsman$deleteFeatureType( idWorkspace, idDataSource, idLayer )
    }
   (...)
```

So, I guess this solve my issue.

Thanks !

**Comment by eblondel** [comment]
Thanks @fxi I will keep watching on the unpublishLayer in case I detect similar issue again, it sounds i got that one in the past, but i could not reproduce it. This could later be an improvement of unpublishLayer if the current implementation is not enough.
