### ISSUE TITLE
Fix createStyle / updateStyle / deleteStyle when workspace is specified

### ISSUE THREAD

**Issue by EvandroStk9** [eblondel/geosapi#64]
Hi,

I'm attempting to upload styles to a specific workspace using the "ws" parameter of the "gsman$createStyle" function. The style creation is successful, but it doesn't associate with any workspace.

R version 4.2.1
GeoServer Version 2.23.0

**Comment by eblondel** [comment]
Thanks @EvandroStk9 i'm going to look ASAP what's wrong on this.

**Comment by eblondel** [comment]
My bad, i've checked and indeed some conditions were writen too quickly. It should be fixed now. Let me know

**Comment by EvandroStk9** [comment]
Thank you @eblondel. It works fine for me now.

**Comment by eblondel** [comment]
For your convenience i've submitted a revision to CRAN, it has been accepted.
